# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# Line length
MD013:
  line_length: 100
  code_blocks: false
  tables: false

# First line should be a top-level heading
MD041: false

# Allow colon at the end of headings:
MD026: false

# Allow inline HTML for collapsible sections and Claude prompting tags
MD033:
  allowed_elements:
    - details
    - summary
    - thinking
    - context
    - examples
    - example
    - instructions
    - constraints
    - answer
