repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(md|markdown)$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--fix]

#  - repo: https://github.com/executablebooks/mdformat
#    rev: 0.7.17
#    hooks:
#      - id: mdformat
#        additional_dependencies:
#          - mdformat-gfm
#          - mdformat-frontmatter
#          - mdformat-footnote

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff-format

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt (check)
        entry: bash -lc 'cd md_linter && cargo fmt --all -- --check'
        language: system
        pass_filenames: false
        stages: [pre-commit]
        files: ^md_linter/.*\.rs$

      - id: cargo-clippy
        name: cargo clippy (deny warnings)
        entry: bash -lc 'cd md_linter && cargo clippy --all-targets --all-features -- -D warnings'
        language: system
        pass_filenames: false
        stages: [pre-commit]
        files: ^md_linter/.*\.rs$

      - id: typos
        name: typos (spellcheck)
        entry: bash -lc 'typos'
        language: system
        pass_filenames: false
        stages: [pre-commit]
