name: Test PyPI - VM Package

on:
  workflow_dispatch:
    inputs:
      version_suffix:
        description: 'Version suffix (e.g., dev1, rc1). Leave empty for current version'
        required: false
        type: string
        default: ''

jobs:
  deploy-to-test-pypi:
    uses: ./.github/workflows/publish-vm-pypi.yml
    with:
      use_test_pypi: true
      version_suffix: ${{ github.event.inputs.version_suffix }}
    secrets: inherit
